name: ðŸ“– Publish Docs

on:
  push:
    paths:
      - docs/**
      - src/**
      - mkdocs.yml
    branches: [dev]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  # build_openapi_json:
  #   uses: hotosm/gh-workflows/.github/workflows/openapi_build.yml@3.4.1
  #   with:
  #     image: ghcr.io/${{ github.repository }}/backend:ci-${{ github.ref_name }}
  #     example_env_file_path: ".env.example"
  #     output_path: docs/openapi.json

  publish_docs:
    uses: hotosm/gh-workflows/.github/workflows/mkdocs_build.yml@3.4.1
    # needs:
    #   - build_openapi_json
    # with:
    #   openapi: true
